---
title: "Selectivity_and_Logistic_Regressions"
author: "Alyssa Herrera"
date: "2025-07-15"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Selectivity Analysis
```{r}
#Loading Packages
library(readxl)
library(tidyr)
library(dplyr)
library(writexl)
library(ggplot2)
library(purrr)
library(emmeans)
library(dplyr)
library(lme4)
library(olsrr)
library(broom)
library(selectapref)
library(car)
library(corrplot)
library(MASS)

#Loading Data
Diet_Selectivity <- read.csv("Diet_Selectivity.csv")
View(Diet_Selectivity)

Diet_Selectivity = Diet_Selectivity %>%
  group_by(Year, Period, Region, Site)%>%
  mutate(adjusted_TT_count_plus_one = ifelse(adjusted_TT_count == 0, 1, adjusted_TT_count))%>%
   mutate(Total_Species_plus_one = sum(adjusted_TT_count_plus_one, na.rm = TRUE))%>%
  mutate(TT_Proportion_plus_one= (adjusted_TT_count_plus_one/Total_Species_plus_one))%>%
  mutate(adjusted_TT_Density=(adjusted_TT_count/TT_sample_size))%>%
  dplyr::select(1:28, adjusted_TT_count_plus_one, Total_Species_plus_one, TT_Proportion_plus_one, everything())
View(Diet_Selectivity)

# Filter the data for sample sizes larger than 9 eels
Diet_Selectivity_filtered <- Diet_Selectivity %>%
  filter(Eel_sample_size > 9)

# Calculate E* using number of prey in environment (Use this code)
Eelectivity_and_Selectivity <- Diet_Selectivity_filtered %>%
  filter(!(Prey_Type %in% c("UknownInsects", "Miscellaneous"))) %>%
  group_by(Year, Site, Region, Period)%>%
  mutate(Manly_alpha = if_else(
    !is.na(Eel_Proportion) & !is.na(TT_Proportion) & TT_Proportion != 0,
    (Eel_Proportion / TT_Proportion) / (sum(Eel_Proportion / TT_Proportion, na.rm = TRUE)),
    NA_real_))%>%
  mutate(
    Foraging_Ratio = Eel_Proportion / TT_Proportion,  # Calculate foraging ratio
    Foraging_Ratio = ifelse(is.infinite(Foraging_Ratio), NA, Foraging_Ratio),  # Convert Inf to NA
    Sum_Foraging_Ratio = sum(Foraging_Ratio, na.rm = TRUE),  # Sum ignoring NAs and Infs
    Sum_Foraging_Ratio = sum(Foraging_Ratio, na.rm = TRUE),  # Sum of foraging ratios
    n = sum(TT_Proportion > 0, na.rm = TRUE),  # Number of prey types
    E_star = ((Foraging_Ratio / Sum_Foraging_Ratio) - (1 / n)) /
             ((Foraging_Ratio / Sum_Foraging_Ratio) + (1 / n)),
    Li = Eel_Proportion - TT_Proportion)
View(Eelectivity_and_Selectivity)

# Transform the data into the desired format
E_star_wide <- Eelectivity_and_Selectivity %>%
  dplyr::select(Year, Region, Site, Period, Prey_Type, E_star) %>%  # Keep relevant columns
  pivot_wider(names_from = Prey_Type, values_from = E_star)%>%
  dplyr::select(Year, Region, Site, Period, Fish, Shrimp, Crayfish, Odonata, Hemiptera, Coleoptera, Gastropoda, Diptera)%>%
  mutate(across(Fish:Diptera, ~replace_na(as.character(round(.x, 4)), "+NA")))
View(E_star_wide)

Li_wide <- Eelectivity_and_Selectivity %>%
  dplyr::select(Year, Region, Site, Period, Prey_Type, Li) %>%  # Keep relevant columns
  pivot_wider(names_from = Prey_Type, values_from = Li)%>%
  dplyr::select(Year, Region, Site, Period, Fish, Shrimp, Crayfish, Odonata, Hemiptera, Coleoptera, Gastropoda, Diptera)%>%
  mutate(across(Fish:Diptera, ~replace_na(as.character(round(.x, 4)), "+NA")))
View(Li_wide)
```

###Selectivity Plots

```{r}
#Load data
Li_wide <- read.csv("Selectivity_Strauss.csv")

#T-tests to test significance of selection (or avoidance)
Li_wide$Gastropoda <- as.numeric(Li_wide$Gastropoda)
t.test(Li_wide$Gastropoda, mu = 0)
Li_wide$Coleoptera <- as.numeric(Li_wide$Coleoptera)
t.test(Li_wide$Coleoptera, mu = 0)
Li_wide$Diptera <- as.numeric(Li_wide$Diptera)
t.test(Li_wide$Diptera, mu = 0)
Li_wide$Crayfish <- as.numeric(Li_wide$Crayfish)
t.test(Li_wide$Crayfish, mu = 0)
Li_wide$Odonata <- as.numeric(Li_wide$Odonata)
t.test(Li_wide$Odonata, mu = 0)
Li_wide$Hemiptera <- as.numeric(Li_wide$Hemiptera)
t.test(Li_wide$Hemiptera, mu = 0)
Li_wide$Fish <- as.numeric(Li_wide$Fish)
t.test(Li_wide$Fish, mu = 0)
Li_wide$Shrimp <- as.numeric(Li_wide$Shrimp)
t.test(Li_wide$Shrimp, mu = 0)

#T-tests ommitting 0 values
Li_wide$Crayfish <- as.numeric(Li_wide$Crayfish)
t.test(Li_wide$Crayfish[Li_wide$Crayfish != 0], mu = 0)
Li_wide$Diptera <- as.numeric(Li_wide$Diptera)
t.test(Li_wide$Diptera[Li_wide$Diptera != 0], mu = 0)
Li_wide$Coleoptera <- as.numeric(Li_wide$Coleoptera)
t.test(Li_wide$Coleoptera[Li_wide$Coleoptera != 0], mu = 0)
Li_wide$Gastropoda <- as.numeric(Li_wide$Gastropoda)
t.test(Li_wide$Gastropoda[Li_wide$Gastropoda != 0], mu = 0)

#Arranging data for figure
Li_wide$sample_id <- paste(Li_wide$Year, Li_wide$Region, Li_wide$Site, Li_wide$Period, sep = "_")

prey_types <- c("Fish", "Shrimp", "Crayfish", "Odonata", 
                "Hemiptera", "Coleoptera", "Gastropoda", "Diptera")

t_results <- data.frame(prey_type = character(),t_value = numeric(),
  stringsAsFactors = FALSE)

for (prey in prey_types) {
  values <- as.numeric(Li_wide[[prey]])
  t_val <- tryCatch(t.test(values, mu = 0)$statistic, error = function(e) NA_real_)
  t_results <- rbind(t_results, data.frame(prey_type = prey, t_value = t_val))}

# Reshape to long format
Li_long <- Li_wide %>%
  pivot_longer(cols = all_of(prey_types), names_to = "prey_type", values_to = "value") %>%
  mutate(sample_id = paste(Year, Region, Site, Period, sep = "_"))

Li_long <- Li_long %>%
  group_by(prey_type) %>%
  mutate(norm_value = value / max(abs(value), na.rm = TRUE)) %>%
  ungroup()

#Average across site
# Summarize mean LI per prey type with 95% CI
LI_summary <- Li_long %>%
  group_by(prey_type) %>%
  summarise(
    mean_LI = mean(value[value != 0], na.rm = TRUE),
    se = sd(value, na.rm = TRUE) / sqrt(n()),
    ci_low = mean_LI - qt(0.975, df = n() - 1) * se,
    ci_high = mean_LI + qt(0.975, df = n() - 1) * se,
    .groups = "drop")

LI_summary_2 <- Li_long %>%
  left_join(LI_summary, by = "prey_type")

#with Original data points
# Set desired order first
LI_summary_2$prey_type <- factor(LI_summary_2$prey_type,
                                 levels = c("Crayfish", "Odonata",  "Fish", "Shrimp", "Hemiptera","Coleoptera", "Diptera", "Gastropoda"))

LI_summary_2$prey_type <- factor(LI_summary_2$prey_type,
  levels = c("Crayfish", "Odonata", "Fish", "Shrimp", "Hemiptera", 
             "Coleoptera", "Diptera", "Gastropoda"),
  labels = c("Crayfish", "Dragonfly naiads", "Fish", "Grass shrimp", "Aquatic bugs", "Beetles", "Fly larvae", "Snails"))

#Final Plot
Linear_Index_Graph <- ggplot(LI_summary_2, aes(x = prey_type, y = value)) + 
  geom_jitter(data = subset(LI_summary_2, value != 0),
              width = 0.2, color = "grey60", size = 0.5, alpha = 1) +
  geom_point(aes(y = mean_LI), 
             shape = 21, fill = "black", color = "black", size = 0.5, stroke = 1) +
  geom_errorbar(aes(ymin = ci_low, ymax = ci_high), 
                color = "black", width = 0.5, size = 0.3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.3) +
  theme_minimal() +
  labs(
    x = "Prey type",
    y = expression("Linear index ( " * paste(italic(L[i])) * ")")
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    axis.text.y = element_text(size = 9),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    legend.position = "none",
  panel.grid.major = element_blank(),     
  panel.grid.minor = element_blank(),     
  panel.border = element_blank(),         
  axis.line = element_line(color = "black", size = 0.3)) +
  scale_y_continuous(
    limits = c(-0.7, 0.7),
    breaks = seq(-1, 1, by = 0.2))
Linear_Index_Graph

ggsave("Linear_Index_Graph.eps", Linear_Index_Graph, width = 3.307, height = 3, dpi = 800)
```

#Energetics GLM
```{r}
prey_calories <- read.csv("Prey_Calories.csv")
View(prey_calories)

names(prey_calories)[names(prey_calories) == "Prey Type"] <- "Prey.Type"

#check/correct normality
hist(prey_calories$Calories)

#log tranform variable
prey_calories$logCalories <- log(prey_calories$Calories)
hist(prey_calories$logCalories)

#Model
calories.glm = lm(prey_calories$logCalories ~ Prey.Type, data = prey_calories)
summary(calories.glm)
plot(calories.glm)

#Pairwise model
pairs(emmeans(calories.glm, ~ Prey.Type))
qqnorm(prey_calories$logCalories)

shapiro.test(residuals(calories.glm))
leveneTest(calories.glm)

#GLM with Gamma distribution for skewness
calories.glm_gamma <- glm(Calories ~ Prey.Type, data = prey_calories,family = Gamma(link = "log"))
summary(calories.glm_gamma)

pairs(emmeans(calories.glm_gamma, ~ Prey.Type))

plot(calories.glm_gamma)

#Checking Heteroscedasticity
plot(fitted(calories.glm_gamma), 
     residuals(calories.glm_gamma, type = "deviance"),
     xlab = "Fitted values", 
     ylab = "Deviance residuals")+
abline(h = 0, lty = 2)

#Residuals check
qqnorm(resid_dev)

#Difference in Medians
kruskal.test(Calories ~ Prey.Type, data = prey_calories)

library(FSA)
dunnTest(Calories ~ Prey.Type, data = prey_calories, method="bonferroni")
```

#Logistic Regressions
```{r}
#Loading Data
eels2 <- read.csv("Logistic_Regression_Data.csv")

#Correlation Matrix
# Select the relevant columns for correlation analysis
selected_columns <- c("TL_mm", "TT_Mean_Count_Fish", "TT_Mean_Count_Odonata", "TT_Mean_Count_Shrimp", "TT_Mean_Count_Hemiptera", "TT_Mean_Count_Crayfish")

# Calculate the correlation matrix
correlation_matrix <- cor(eels2[, selected_columns], use = "complete.obs")
corrplot(correlation_matrix, method = "color", 
         type = "upper", 
         tl.col = "black", 
         tl.srt = 45, 
         addCoef.col = "black")

#Size Cuttoff
eels2_large<- subset(eels2, TL_mm >250)

#Testing for species differences (Monopterus albus vs. javanensis)
eels2_region <- eels2_large %>%
  mutate(Region_Group = case_when(
    Region %in% c("SRS", "TSL", "PHD") ~ "ENP",
    Region %in% c("WCA 3A", "WCA 3B", "GAP") ~ "WCA",
    TRUE ~ Region ))

eels2_region <- eels2_large %>%
  filter(!Region %in% c("TSL", "PHD")) %>%
  mutate(Region_Group = case_when(
    Region %in% c("SRS") ~ "ENP",
    Region %in% c("WCA 3A", "WCA 3B", "GAP") ~ "WCA",
    TRUE ~ Region))
```

##Crayfish
```{r}
#FITTING THE MODEL
Crayfish_glm = glm(Eel_Presence_Crayfish ~ TL_mm+ TT_Mean_Count_Crayfish+TT_Mean_Count_Fish+TT_Mean_Count_Hemiptera+TT_Mean_Count_Odonata +TT_Mean_Count_Shrimp, family = "binomial" (link = "logit"), data = eels2)
summary(Crayfish_glm)

# Stepwise with significance levels 
ols_step_both_p(
  Crayfish_glm,
  pent = 0.1,   # predictor must have p ≤ 0.1 to enter
  prem = 0.1,   # predictor removed if p > 0.1
  details = TRUE)

#reduced model
Crayfish_glm = glm(Eel_Presence_Crayfish ~ (TL_mm)+ (TT_Mean_Count_Crayfish)+ (TT_Mean_Count_Shrimp), family = "binomial" (link = "logit"), data = eels2)
summary(Crayfish_glm)

library(effects)
plot(allEffects(Crayfish_glm), multiline = TRUE, rug = TRUE)

ggplot(eels2, aes(x = TT_Mean_Count_Crayfish, y = Eel_Presence_Crayfish)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.5, color = "blue") +
  geom_smooth(method = "glm", method.args = list(family = "binomial"),
              se = TRUE, color = "red") +
  labs(x = "Crayfish Density", y = "Eel Presence (0/1)",
       title = "Eel Presence vs. Crayfish Density") +
  theme_minimal()

# predictor selection/model refinement
library(olsrr)
vif(Crayfish_glm)

#CHECKING ASSUMPTIONS
##4. Linearity of predictors with logit of the response

#added variable plots
avPlots(Crayfish_glm, ask = FALSE)

#Partial Residual Plot
eels2 %>% 
  mutate(comp_res_cray = coef(Crayfish_glm)["TT_Mean_Count_Crayfish"] * TT_Mean_Count_Crayfish +residuals(Crayfish_glm, type = "working")) %>%
  ggplot(aes(x = TT_Mean_Count_Crayfish, y = comp_res_cray)) +
    geom_point(alpha = 0.6) +
    geom_smooth(method = "lm", color = "red", linetype = "dashed", se = FALSE) +
    geom_smooth(se = FALSE) +
    labs(x = "Crayfish Density (TT_Mean_Count_Crayfish)",
      y = "Component + Residual",
      title = "Partial‐Residual Plot for Crayfish Density") +
    theme_minimal()

#large eels
Crayfish_glm = glm(Eel_Presence_Crayfish ~ TL_mm+ TT_Mean_Count_Crayfish +TT_Mean_Count_Fish+TT_Mean_Count_Hemiptera+TT_Mean_Count_Odonata+TT_Mean_Count_Shrimp, family = "binomial" (link = "logit"), data = eels2_large)
summary(Crayfish_glm)

vif(Crayfish_glm)

# Stepwise with significance levels 
ols_step_both_p(
  Crayfish_glm,
  pent = 0.1,   # predictor must have p ≤ 0.1 to enter
  prem = 0.1,   # predictor removed if p > 0.1
  details = TRUE)

Crayfish_glm = glm(Eel_Presence_Crayfish ~ TL_mm+ TT_Mean_Count_Crayfish +TT_Mean_Count_Shrimp, family = "binomial" (link = "logit"), data = eels2_large)
summary(Crayfish_glm)

cray = ggplot(eels2_large, aes(x = TT_Mean_Count_Crayfish, y = Eel_Presence_Crayfish)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.3) +
  stat_smooth(method = "glm", method.args = list(family = "binomial"), color = "darkgreen") +
  labs(
    x = "Crayfish Density",
    y = "Probability of Crayfish in Diet",
    title = "Observed and Fitted Relationship"
  ) +
  theme_minimal(base_size = 14)

fih = ggplot(eels2_large, aes(x = TT_Mean_Count_Fish, y = Eel_Presence_Crayfish)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.3) +
  stat_smooth(method = "glm", method.args = list(family = "binomial"), color = "darkgreen") +
  labs(
    x = "Fish Density",
    y = "Probability of Crayfish in Diet",
    title = "Observed and Fitted Relationship"
  ) +
  theme_minimal(base_size = 14)

hemiptera = ggplot(eels2_large, aes(x = TT_Mean_Count_Hemiptera, y = Eel_Presence_Crayfish)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.3) +
  stat_smooth(method = "glm", method.args = list(family = "binomial"), color = "darkgreen") +
  labs(
    x = "Aquatic Bug Density",
    y = "Probability of Crayfish in Diet",
    title = "Observed and Fitted Relationship"
  ) +
  theme_minimal(base_size = 14)
hemiptera

Odonata = ggplot(eels2_large, aes(x = TT_Mean_Count_Odonata, y = Eel_Presence_Crayfish)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.3) +
  stat_smooth(method = "glm", method.args = list(family = "binomial"), color = "darkgreen") +
  labs(
    x = "Odonate Density",
    y = "Probability of Crayfish in Diet",
    title = "Odonata"
  ) +
  theme_minimal(base_size = 14)

Shrimp = ggplot(eels2_large, aes(x = TT_Mean_Count_Shrimp, y = Eel_Presence_Crayfish)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.3) +
  stat_smooth(method = "glm", method.args = list(family = "binomial"), color = "darkgreen") +
  labs(
    x = "Shrimp Density",
    y = "Probability of Crayfish in Diet",
    title = "Shrimp"
  ) +
  theme_minimal(base_size = 14)
Shrimp

library(gridExtra)

grid.arrange(cray, fih, hemiptera, Odonata, Shrimp, ncol = 5)
View(figure)

eels_clean <- na.omit(eels2_large[, c("Eel_Presence_Crayfish","Eel_Presence_Fish", "Eel_Presence_Odonata", "Eel_Presence_Shrimp", "Eel_Presence_Hemiptera",
                                      "TL_mm",
                                      "TT_Mean_Count_Crayfish",
                                      "TT_Mean_Count_Fish",
                                      "TT_Mean_Count_Hemiptera",
                                      "TT_Mean_Count_Odonata",
                                      "TT_Mean_Count_Shrimp")])

library(ROCR)

pred <- predict(Crayfish_glm, type = "response")

# Prediction and performance objects
pred_obj <- prediction(pred, eels_clean$Eel_Presence_Crayfish)

perf <- performance(pred_obj, "tpr", "fpr")

length(pred)
length(eels_clean$Eel_Presence_Crayfish)
# Plot ROC curve
plot(perf, colorize = TRUE)

# AUC
auc_obj <- performance(pred_obj, "auc")
auc_obj@y.values[[1]]

#Species differences
Crayfish_glm = glm(Eel_Presence_Crayfish ~ TL_mm+ TT_Mean_Count_Crayfish*Region_Group+TT_Mean_Count_Fish+TT_Mean_Count_Odonata+TT_Mean_Count_Shrimp+TT_Mean_Count_Hemiptera, family = "binomial" (link = "logit"), data = eels2_region)
summary(Crayfish_glm)

Crayfish_glm = glm(Eel_Presence_Crayfish ~  TT_Mean_Count_Crayfish*Region_Group, family = "binomial" (link = "logit"), data = eels2_region)
summary(Crayfish_glm)

## MODEL SUMMARY TABLE
model_summary <- summary(Crayfish_glm)
# Extract coefficients and p-values
coefficients <- model_summary$coefficients
p_values <- coefficients[, "Pr(>|z|)"]
odds_ratios <- exp(coefficients[, "Estimate"])
conf_intervals <- exp(confint(Crayfish_glm))
# Calculate probabilities from the odds ratios:
probabilities <- odds_ratios / (1 + odds_ratios)
# Combine into a summary table
results.cray <- data.frame(
  Predictor = rownames(coefficients),
  Estimate = coefficients[, "Estimate"],
  Std_Error = coefficients[, "Std. Error"],
  Odds_Ratio = odds_ratios,
  `2.5% CI` = conf_intervals[, 1],
  `97.5% CI` = conf_intervals[, 2],
  Probability = probabilities,
  P_Value = p_values)
results.cray[, -1] <- round(results.cray[, -1], 3)
View(results.cray)
```

##Fish
```{r}
#Fitting the model
Fish_glm = glm(Eel_Presence_Fish ~ TL_mm+TT_Mean_Count_Crayfish+ TT_Mean_Count_Fish+TT_Mean_Count_Hemiptera+TT_Mean_Count_Odonata+ TT_Mean_Count_Shrimp, family = "binomial", data = eels2)
summary(Fish_glm)

# Stepwise with significance levels 
ols_step_both_p(
  Fish_glm,
  pent = 0.1,   # predictor must have p ≤ 0.1 to enter
  prem = 0.1,   # predictor removed if p > 0.1
  details = TRUE)

vif(Fish_glm)

Fish_glm = glm(Eel_Presence_Fish ~ TL_mm+TT_Mean_Count_Odonata, family = "binomial", data = eels2)
summary(Fish_glm)

ggplot(eels2, aes(x = TT_Mean_Count_Fish, y = Eel_Presence_Fish)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.5, color = "blue") +
  geom_smooth(method = "glm", method.args = list(family = "binomial"),
              se = TRUE, color = "red") +
  labs(x = "Fish Density", y = "Eel Presence (0/1)",
       title = "Eel Presence vs. Fish Density") +
  theme_minimal()

avPlots(Fish_glm, ask = FALSE)

# Model summary
model_summary <- summary(Fish_glm)

# Extract coefficients and p-values
coefficients <- model_summary$coefficients
p_values <- coefficients[, "Pr(>|z|)"]

odds_ratios <- exp(coefficients[, "Estimate"])
conf_intervals <- exp(confint(Fish_glm))
probabilities <- odds_ratios / (1 + odds_ratios)
# Combine into a summary table
results.fish <- data.frame(
  Predictor = rownames(coefficients),
  Estimate = coefficients[, "Estimate"],
  Std_Error = coefficients[, "Std. Error"],
  Odds_Ratio = odds_ratios,
  `2.5% CI` = conf_intervals[, 1],
  `97.5% CI` = conf_intervals[, 2],
  Probability = probabilities,
  P_Value = p_values)
results.fish[, -1] <- round(results.fish[, -1], 3)
View(results.fish)


# Plotting
ggplot(prediction_data, aes(x = TT_Proportion, y = predicted_proportion)) +
  geom_line() +
  labs(title = "Predicted Eel Proportion by Fish Proportion",
       x = "Fish Proportion (TT_Proportion)",
       y = "Predicted Eel Proportion") +
  theme_minimal()

vif(Fish_glm)
plot(allEffects(Fish_glm))

#large eels (>250mm TL)
Fish_glm = glm(Eel_Presence_Fish ~ TL_mm+ TT_Mean_Count_Crayfish+TT_Mean_Count_Fish+ TT_Mean_Count_Hemiptera+TT_Mean_Count_Odonata+ TT_Mean_Count_Shrimp+TT_Mean_Count_Fish, family = "binomial", data = eels2_large)
summary(Fish_glm)
vif(Fish_glm)

Fish_glm = glm(Eel_Presence_Fish ~TT_Mean_Count_Crayfish*TT_Mean_Count_Fish, family = "binomial", data = eels2_large)

# Stepwise with significance levels 
ols_step_both_p(
  Fish_glm,
  pent = 0.1,   
  prem = 0.1,   
  details = TRUE)

Fish_glm = glm(Eel_Presence_Fish ~ TL_mm+TT_Mean_Count_Odonata, family = "binomial", data = eels_clean)
summary(Fish_glm)

#Calculatin AUC
pred <- predict(Fish_glm, type = "response")

length(pred)
length(eels_clean$Eel_Presence_Fish)

# Prediction and performance objects
pred_obj <- prediction(pred, eels_clean$Eel_Presence_Fish)

perf <- performance(pred_obj, "tpr", "fpr")

# Plot ROC curve
plot(perf, colorize = TRUE)

# AUC
auc_obj <- performance(pred_obj, "auc")
auc_obj@y.values[[1]]  

#species differences
Fish_glm = glm(Eel_Presence_Fish ~ TL_mm+ TT_Mean_Count_Crayfish*Region_Group+TT_Mean_Count_Fish+TT_Mean_Count_Odonata+TT_Mean_Count_Shrimp+TT_Mean_Count_Hemiptera, family = "binomial" (link = "logit"), data = eels2_region)
summary(Fish_glm)

Fish_glm = glm(Eel_Presence_Fish ~ TL_mm+ TT_Mean_Count_Crayfish*Region_Group, family = "binomial" (link = "logit"), data = eels2_region)
summary(Fish_glm)
```

##Odonata
```{r}
#Fitting the model (Keep full model)
Odonata_glm = glm(Eel_Presence_Odonata ~ TL_mm+ TT_Mean_Count_Crayfish+ TT_Mean_Count_Fish+ +TT_Mean_Count_Hemiptera+TT_Mean_Count_Odonata +TT_Mean_Count_Shrimp , family = "binomial" (link = "logit"), data = eels2)
summary(Odonata_glm)

# Stepwise with significance levels 
ols_step_both_p(
  Odonata_glm,
  pent = 0.1,
  prem = 0.1,   
  details = TRUE)

vif(Odonata_glm)

#Reduced Model
Odonata_glm = glm(Eel_Presence_Odonata ~ TT_Mean_Count_Odonata+ TT_Mean_Count_Crayfish, family = "binomial", data = eels2)
summary(Odonata_glm)

ggplot(eels2, aes(x = TT_Mean_Count_Odonata, y = Eel_Presence_Odonata)) +
  geom_jitter(height = 0.05, width = 0, alpha = 0.5, color = "blue") +
  geom_smooth(method = "glm", method.args = list(family = "binomial"),
              se = TRUE, color = "red") +
  labs(x = "Odonata Density", y = "Eel Presence (0/1)",
       title = "Eel Presence vs. Odonata Density") +
  theme_minimal()

##CHECKING LINEARITY
#added variable plots
avPlots(Odonata_glm, ask = FALSE)

# Model summary
model_summary <- summary(Odonata_glm)
# Extract coefficients and p-values
coefficients <- model_summary$coefficients
p_values <- coefficients[, "Pr(>|z|)"]
# Calculate odds ratios and confidence intervals
odds_ratios <- exp(coefficients[, "Estimate"])
conf_intervals <- exp(confint(Odonata_glm))
probabilities <- odds_ratios / (1 + odds_ratios)
# Combine into a summary table
results.odonata <- data.frame(
  Predictor = rownames(coefficients),
  Estimate = coefficients[, "Estimate"],
  Std_Error = coefficients[, "Std. Error"],
  Odds_Ratio = odds_ratios,
  `2.5% CI` = conf_intervals[, 1],
  `97.5% CI` = conf_intervals[, 2],
  Probability = probabilities,
  P_Value = p_values)
results.odonata[, -1] <- round(results.odonata[, -1], 3)
View(results.odonata)

#Large eels (>250 mm TL)
Odonata_glm = glm(Eel_Presence_Odonata ~ TL_mm+ TT_Mean_Count_Crayfish+ TT_Mean_Count_Fish +TT_Mean_Count_Hemiptera+TT_Mean_Count_Odonata+TT_Mean_Count_Shrimp , family = "binomial" (link = "logit"), data = eels2_large)
summary(Odonata_glm)

# Stepwise with significance levels 
ols_step_both_p(
  Odonata_glm,
  pent = 0.1,   
  prem = 0.1,   
  details = TRUE)

Odonata_glm = glm(Eel_Presence_Odonata ~ TT_Mean_Count_Odonata+ TT_Mean_Count_Crayfish, family = "binomial" (link = "logit"), data = eels2_large)
summary(Odonata_glm)
vif(Odonata_glm)

Odonata_glm = glm(Eel_Presence_Odonata ~ TT_Mean_Count_Odonata* TT_Mean_Count_Fish, family = "binomial" (link = "logit"), data = eels2_large)

#Calculating AUC
pred <- predict(Odonata_glm, type = "response")

# Prediction and performance objects
pred_obj <- prediction(pred, eels_clean$Eel_Presence_Odonata)

perf <- performance(pred_obj, "tpr", "fpr")

# Plot ROC curve
plot(perf, colorize = TRUE)

# AUC
auc_obj <- performance(pred_obj, "auc")
auc_obj@y.values[[1]]  

#Species differences
Odonata_glm = glm(Eel_Presence_Odonata ~ TL_mm+ TT_Mean_Count_Crayfish*Region_Group+ TT_Mean_Count_Odonata+TT_Mean_Count_Fish+ TT_Mean_Count_Hemiptera+TT_Mean_Count_Shrimp, family = "binomial" (link = "logit"), data = eels2_region)
summary(Odonata_glm)

Odonata_glm = glm(Eel_Presence_Odonata ~  TT_Mean_Count_Crayfish*Region_Group, family = "binomial" (link = "logit"), data = eels2_region)
summary(Odonata_glm)
```

##Shrimp
```{r}
#Fitting the model
Shrimp_glm = glm(Eel_Presence_Shrimp ~ TL_mm  +TT_Mean_Count_Crayfish+ TT_Mean_Count_Fish +TT_Mean_Count_Hemiptera+TT_Mean_Count_Shrimp, family = "binomial", data = eels2)
summary(Shrimp_glm)

# Stepwise with significance levels 
ols_step_both_p(
  Shrimp_glm,
  pent = 0.1,   # predictor must have p ≤ 0.1 to enter
  prem = 0.1,   # predictor removed if p > 0.1
  details = TRUE)

vif(Shrimp_glm)

Shrimp_glm = glm(Eel_Presence_Shrimp ~ TT_Mean_Count_Shrimp +TT_Mean_Count_Crayfish, family = "binomial", data = eels2)
summary(Shrimp_glm)

ggplot(eels2, aes(x = TT_Mean_Count_Shrimp, y = Eel_Presence_Shrimp)) +geom_jitter(height = 0.05, width = 0, alpha = 0.5, color = "blue") +
geom_smooth(method = "glm", method.args = list(family = "binomial"),
se = TRUE, color = "red") +labs(x = "Shrimp Density", y = "Eel Presence (0/1)",title = "Eel Presence vs. Shrimp Density") +
theme_minimal()

#Model Summary
model_summary <- summary(Shrimp_glm)
# Extract coefficients and p-values
coefficients <- model_summary$coefficients
p_values <- coefficients[, "Pr(>|z|)"]
odds_ratios <- exp(coefficients[, "Estimate"])
conf_intervals <- exp(confint(Shrimp_glm))
probabilities <- odds_ratios / (1 + odds_ratios)
# Combine into a summary table
results.shrimp <- data.frame(
  Predictor = rownames(coefficients),
  Estimate = coefficients[, "Estimate"],
  Std_Error = coefficients[, "Std. Error"],
  Odds_Ratio = odds_ratios,
  `2.5% CI` = conf_intervals[, 1],
  `97.5% CI` = conf_intervals[, 2],
  Probability = probabilities,
  P_Value = p_values)
results.shrimp[, -1] <- round(results.shrimp[, -1], 3)
View(results.shrimp)

#Large eels (>250 mm TL)
Shrimp_glm = glm(Eel_Presence_Shrimp ~ TL_mm  +TT_Mean_Count_Crayfish+ TT_Mean_Count_Fish +TT_Mean_Count_Hemiptera+TT_Mean_Count_Odonata+ TT_Mean_Count_Shrimp, family = "binomial", data = eels2_large)
summary(Shrimp_glm)

# Stepwise with significance levels 
ols_step_both_p(
  Shrimp_glm,
  pent = 0.1,   
  prem = 0.1,   
  details = TRUE)

Shrimp_glm = glm(Eel_Presence_Shrimp ~ TT_Mean_Count_Shrimp +TT_Mean_Count_Crayfish , family = "binomial", data = eels2_large)
summary(Shrimp_glm)

#Calculatin AUC
pred <- predict(Shrimp_glm, type = "response")

# Prediction and performance objects
pred_obj <- prediction(pred, eels_clean$Eel_Presence_Shrimp)

perf <- performance(pred_obj, "tpr", "fpr")

# Plot ROC curve
plot(perf, colorize = TRUE)

# AUC
auc_obj <- performance(pred_obj, "auc")
auc_obj@y.values[[1]]

#Species Differences
Shrimp_glm = glm(Eel_Presence_Shrimp ~ TL_mm+ TT_Mean_Count_Crayfish*Region_Group+TT_Mean_Count_Shrimp+TT_Mean_Count_Fish+TT_Mean_Count_Odonata+ TT_Mean_Count_Hemiptera+TT_Mean_Count_Fish, family = "binomial" (link = "logit"), data = eels2_region)
summary(Shrimp_glm)

Shrimp_glm = glm(Eel_Presence_Shrimp ~ TL_mm+ TT_Mean_Count_Shrimp*Region_Group, family = "binomial" (link = "logit"), data = eels2_region)
summary(Shrimp_glm)
```

##Hemiptera
```{r}
#Fitting the model
Hemiptera_glm = glm(Eel_Presence_Hemiptera ~ TL_mm+ TT_Mean_Count_Crayfish+ TT_Mean_Count_Fish +TT_Mean_Count_Hemiptera + TT_Mean_Count_Odonata+TT_Mean_Count_Shrimp, family = "binomial", data = eels2)
summary(Hemiptera_glm)

vif(Hemiptera_glm)

# Stepwise with significance levels 
ols_step_both_p(
  Hemiptera_glm,
  pent = 0.1,   # predictor must have p ≤ 0.1 to enter
  prem = 0.1,   # predictor removed if p > 0.1
  details = TRUE)

Hemiptera_glm = glm(Eel_Presence_Hemiptera ~TT_Mean_Count_Crayfish + TT_Mean_Count_Odonata , family = "binomial", data = eels2)
summary(Hemiptera_glm)

#Model Summary
model_summary <- summary(Hemiptera_glm)
# Extract coefficients and p-values
coefficients <- model_summary$coefficients
p_values <- coefficients[, "Pr(>|z|)"]
odds_ratios <- exp(coefficients[, "Estimate"])
conf_intervals <- exp(confint(Hemiptera_glm))
probabilities <- odds_ratios / (1 + odds_ratios)
# Combine into a summary table
results.hemiptera <- data.frame(
  Predictor = rownames(coefficients),
  Estimate = coefficients[, "Estimate"],
  Std_Error = coefficients[, "Std. Error"],
  Odds_Ratio = odds_ratios,
  `2.5% CI` = conf_intervals[, 1],
  `97.5% CI` = conf_intervals[, 2],
  Probability = probabilities,
  P_Value = p_values)
results.hemiptera[, -1] <- round(results.hemiptera[, -1], 3)
View(results.hemiptera)

#large eels
Hemiptera_glm = glm(Eel_Presence_Hemiptera ~ TL_mm+ TT_Mean_Count_Crayfish + TT_Mean_Count_Fish +TT_Mean_Count_Hemiptera*TT_Mean_Count_Crayfish + TT_Mean_Count_Odonata+ TT_Mean_Count_Shrimp, family = "binomial", data = eels2_large)
summary(Hemiptera_glm)

# Stepwise with significance levels 
ols_step_forward_p(
  Hemiptera_glm,
  pent = 0.1,   
  prem = 0.1,   
  details = TRUE)

Hemiptera_glm = glm(Eel_Presence_Hemiptera ~ TL_mm+ TT_Mean_Count_Crayfish + TT_Mean_Count_Odonata, family = "binomial", data = eels2_large)
summary(Hemiptera_glm)
vif(Hemiptera_glm)

#Calculatin AUC
pred <- predict(Hemiptera_glm, type = "response")

# Prediction and performance objects
pred_obj <- prediction(pred, eels_clean$Eel_Presence_Hemiptera)

perf <- performance(pred_obj, "tpr", "fpr")

# Plot ROC curve
plot(perf, colorize = TRUE)

# AUC
auc_obj <- performance(pred_obj, "auc")
auc_obj@y.values[[1]] 

#Species Models
Hemiptera_glm = glm(Eel_Presence_Hemiptera ~ TL_mm+ TT_Mean_Count_Crayfish*Region_Group+TT_Mean_Count_Hemiptera+TT_Mean_Count_Fish+TT_Mean_Count_Odonata+ TT_Mean_Count_Shrimp, family = "binomial" (link = "logit"), data = eels2_region)
summary(Hemiptera_glm)

Hemiptera_glm = glm(Eel_Presence_Hemiptera ~ TL_mm+ TT_Mean_Count_Hemiptera*Region_Group, family = "binomial" (link = "logit"), data = eels2_region)
summary(Hemiptera_glm)
```

```{r}
combined_models <- bind_rows(
  results.cray %>% mutate(Prey = "Crayfish"),
  results.fish     %>% mutate(Prey = "Fish"),
  results.odonata   %>% mutate(Prey = "Dragonfly naiads"),
  results.shrimp %>% mutate(Prey = "Grass shrimp"),
  results.hemiptera %>% mutate(Prey = "Aquatic bugs")
)
View(combined_models)
write_xlsx(combined_models, path = "C:/Users/Alyssa/OneDrive - Florida International University/Asian Swamp Eel Dissection Data (USE ME)/Figures and Results/Logistic Regressions/Full_Logistic_Models_Regional.xlsx")
```

